version: "3.7"
services:
  oauth-lite:
    build: "."
    command: "--ldap-attrs mail uid uidNumber --ldap-url 'ldap://localhost:389' --ldap-bind-dn 'ou=users,dc=example,dc=com' -c 'test=http://localhost/authenticate' -e true -l info"

  nginx:
    image: "nginx:mainline"
    volumes:
      - ./demo/nginx.conf:/etc/nginx/nginx.conf
      - ./demo/default.conf:/etc/nginx/conf.d/default.conf
      - ./demo/index.html:/usr/share/nginx/html/index.html
      - ./demo/private.html:/usr/share/nginx/html/private.html
    ports:
      - 80:80
